version: "3.8"
services:
  springapp:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql
